# -*- coding: utf-8 -*-
"""PrakFiskom_Tasya

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15760ZOv431g5drzMha4fqOXC3yFbGIda
"""



"""Tasya mendorong sebuah meja dengan gaya sebesar 150 N sehingga meja tersebut bisa berpindah sejauh 15 m.

Sementara Biru mendorong meja yang memiliki massa dan ukuran yang sama dengan gaya 300 N dan meja tersebut berpindah sejauh 30 m.

Berapakah besar usaha yang dilakukan oleh Tasya dan Biru?
"""

# Usaha yang dilakukan oleh Tasya
FTasya = 150  # N
dTasya = 15  # m
usaha_Tasya = FTasya * dTasya

# Usaha yang dilakukan oleh Biru
FBiru = 300  # N
dBiru = 30  # m
usaha_Biru = FBiru * dBiru

# Total usaha yang dilakukan oleh Tasya dan Biru
total_usaha = usaha_Tasya + usaha_Biru

# Hasil
print("Usaha yang dilakukan oleh Tasya:", usaha_Tasya, "Joule")
print("Usaha yang dilakukan oleh Biru:", usaha_Biru, "Joule")
print("Total usaha yang dilakukan oleh Tasya dan Biru:", total_usaha, "Joule")